import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signOut, useSession } from "next-auth/react";
import { api } from "~/utils/api";
import { useState } from "react";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-gray-800">
        <div className="flex justify-between px-10 py-5 text-white">
          <div>
            <Link href={"/"} className="pr-5 hover:text-gray-300">
              Home
            </Link>
            <Link href={"/createpost"} className=" hover:text-gray-300">
              Create a post
            </Link>
          </div>
          <div>
            <User />
          </div>
        </div>
        <div>
          <Posts />
        </div>
      </main>
    </>
  );
};

export default Home;

const User = () => {
  const { data: sessionData, status } = useSession();
  const [toggleInfo, setToggleInfo] = useState(false);
  if (status === "loading") return null;
  if (status === "unauthenticated")
    return <Link href={"/api/auth/signin"}>Sign in</Link>;
  return (
    <div className="relative flex text-white">
      <img
        src={sessionData?.user.image ?? ""}
        alt=""
        className="w-12 cursor-pointer rounded-full"
        onClick={() => setToggleInfo(!toggleInfo)}
      />
      {toggleInfo && (
        <div className="absolute top-full right-0 mt-1 flex w-32 flex-col items-center rounded-lg bg-gray-500">
          <span>Hello, {sessionData?.user.name}</span>
          <button onClick={() => void signOut()}>Sign out</button>
        </div>
      )}
    </div>
  );
};

const Posts = () => {
  const { data: posts } = api.post.getAll.useQuery();
  dayjs.extend(relativeTime);
  return (
    <div className="flex flex-wrap justify-center text-white">
      {posts?.map((post) => (
        <div
          key={post.id}
          className="m-3 basis-1/3 rounded-2xl border border-white p-3"
        >
          <div className="flex gap-5 ">
            {post.tags.map((tag) => (
              <div
                key={Math.random()}
                className="rounded-lg border border-green-400 p-1"
              >
                {tag.title}
              </div>
            ))}
          </div>
          <Link
            className="cursor-pointer text-2xl text-green-500"
            href={`/post/${post.id}`}
          >
            {post.title}
          </Link>
          <div className="italic ">{post.summary}</div>
          <div className="flex items-center gap-2">
            <img
              src={post.user.image ?? ""}
              alt=""
              className="w-20 rounded-full"
            />
            <span>{post.user.name}</span>
            {dayjs(post.createdAt).fromNow()}
          </div>
        </div>
      ))}
    </div>
  );
};
